server:
  port: 8080

application:
  title: @project.name@
  version: @project.version@

spring:
  application:
    name: customer
  datasource:
    username: user
    password: pass
    url: jdbc:postgresql://localhost:5432/customer
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        fortmat_sql: true
