server:
  port: 8080

application:
  title: @project.name@
  version: @project.version@

spring:
  application:
    name: customer
  datasource:
    username: user
    password: pass
    url: jdbc:postgresql://postgres:5432/customer
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        fortmat_sql: true
  rabbitmq:
    addresses: rabbitmq:5672
  zipkin:
    base-url: http://zipkin:9411

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka
