services:
  postgres:
    container_name: myservices-postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  zipkin:
    container_name: myservices-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

volumes:
  postgres: