services:
  postgres:
    container_name: myservices-postgres
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
  rabbitmq:
    container_name: myservices-rabbitmq
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  zipkin:
    container_name: myservices-zipkin
    image: openzipkin/zipkin
    ports:
      - "9411:9411"

volumes:
  postgres: