server:
  port: 8081

application:
  title: @project.name@
  version: @project.version@

spring:
  application:
    name: fraud
  datasource:
    username: user
    password: pass
    url: jdbc:postgresql://localhost:5432/fraud
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        fortmat_sql: true

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
